# Generated by Django 3.0.6 on 2020-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('reason', models.TextField(null=True)),
                ('base', models.TextField(null=True)),
                ('experience', models.TextField(null=True)),
                ('difficulty', models.TextField(null=True)),
                ('recommend', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('view_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
