# Generated by Django 3.0.6 on 2020-07-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200727_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
